'use strict';

angular.module('grcApp', [
    'grcApp.constants',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'btford.socket-io',
    'ui.router',
    'ui.bootstrap',
    'dialogs.main',
    'summernote',
    'localytics.directives',
    'truncate',
    'ui.tree',
    'ngFileUpload',
    'cgNotify',
    'html5.placeholder',
    'datatables',
    'checklist-model',
    'datatables.columnfilter',
    'datatables.buttons',
    'datatables.bootstrap',
    'ngCacheBuster',
    'gridshore.c3js.chart',
    'builder',
    'builder.components',
    'nvd3',
    'auth0.lock',
    'angular-jwt'
]);