module.exports = {
	records : [
		"title",
		"_id",
		"status",
		"description",
		"responsibleOrg.orgName",
		"nominatedReviewer._id",
		"responsibleOfficer._id",
		"category",
		"externalFactors.description",
		"externalFactors.trend",
		"reviewType",
		"identifiedAt._id",
		"identifiedAt.title",
		"identifiedAt.status",
		"identifiedAt.description",
		"assessment.risk",
		"assessment.category",
		"assessment.controls._id",
		"assessment.controls.title",
		"assessment.controls.status",
		"assessment.controls.category",
		"assessment.controls.effectiveness",
		"assessment.initialAssessment.cost",
		"assessment.initialAssessment.consequence",
		"assessment.initialAssessment.likelihood",
		"assessment.initialAssessment.rating",
		"assessment.controlledAssessment.cost",
		"assessment.controlledAssessment.consequence",
		"assessment.controlledAssessment.likelihood",
		"assessment.controlledAssessment.rating",
		"overallAssessment.initialRating",
		"overallAssessment.initialCost",
		"overallAssessment.initialConsequence",
		"overallAssessment.initialLikelihood",
		"overallAssessment.controlledConsequence",
		"overallAssessment.controlledLikelihood",
		"overallAssessment.controlledRating",
		"overallAssessment.controlledCost",
		"overallAssessment.targetLikelihood",
		"overallAssessment.targetConsequence",
		"overallAssessment.targetRating",
		"overallAssessment.targetCost"
	],

	reviews : [
		"_id",
		"title",
		"responsibleOrg.orgName",
		"scheduledBy._id",
		"reviewType",
		"status",
		"description"
	],

	actionItems : [
		"_id",
		"refEntityId",
		"refEntityType",
		"assignedTo._id",
		"createdBy._id",
		"responsibleOrg.orgName",
		"reviewType",
		"title",
		"description",
		"actionRequired",
		"status",
		"priority",
		"dueDate"
	],

	controls : [
		"title",
		"_id",
		"status",
		"effectiveFrom",
		"effectiveTo",
		"responsibleOrg.orgName",
		"responsibleUser._id",
		"category",
		"tag",
		"description"
	]
};